api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'  # Application name

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderListView

app_name = 'orders'  # application name

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),

]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from products import views
from products.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('products/', include('products.my_urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

handler404 = page_not_found  # will be called whenever a 404 error occurs

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models

from users.models import User


# Create your models here.

class Order(models.Model):
    """ The class performs the function of storing information about the customer and his orders """

    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'Order №{self.id}. {self.first_name} {self.last_name} '

products/models.py
from django.db import models
from users.models import User
from typing import Tuple


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.name}'

    class Meta:
        verbose_name_plural: str = 'Категории'  # Name in the admin panel


class Product(models.Model):
    name = models.CharField(max_length=256, unique=True, verbose_name='Имя товара')
    description = models.TextField(verbose_name='Описание товара')
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0)  # Quantity of goods in stock
    image = models.ImageField(upload_to='products_images', verbose_name='Фото')
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT, verbose_name='Категории')

    def __str__(self) -> str:
        return f'Продукт: {self.name} | Категория: {self.category.name}'

    class Meta:
        verbose_name_plural: str = 'Товары в магазине'


class BasketQuerySet(models.QuerySet):

    def total_sum(self) -> int:
        return sum(basket.sum() for basket in self)

    def total_quantity(self) -> int:
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Корзина пользователя')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар в корзине')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество добавленных товаров в корзину')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления в корзину')
    objects = BasketQuerySet.as_manager()  # I use BasketQuerySet as a manager

    def __str__(self) -> str:
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self) -> int:
        return self.product.price * self.quantity

    class Meta:
        verbose_name_plural: str = 'Корзина товаров'  # Name in the admin panel

    @classmethod
    def create_or_update(cls, product_id: int, user) -> Tuple:
        product = Product.objects.get(id=product_id)
        baskets_items = Basket.objects.filter(user=user,
                                              product=product).first()  # I take the user's cart with a certain product

        if not baskets_items:
            obj = Basket.objects.create(user=user, product=product, quantity=1)
            is_created = True
            return obj, is_created
        else:
            baskets_items.quantity += 1
            baskets_items.save()
            is_created = False
            return baskets_items, is_created

orders/forms.py
from django import forms
from orders.models import Order


class OrderForm(forms.ModelForm):
    """ Form for working with orders """

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ринат'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Усманов'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Россия, Москва, ул. Мира, дом 6'}
                                       ),
        }

orders/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order


class OrderCreateView(TitleMixin, CreateView):
    """ The class places an order for the client """
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'zhigalev_store - Оформление заказа'

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


class OrderListView(TitleMixin, ListView):
    """ The class shows a page with customer orders """

    template_name = 'orders/orders.html'
    title = 'zhigalev_store - Заказы'
    queryset = Order.objects.all()

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}

{% block content %}
<section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{user.basket_set.all.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in user.basket_set.all %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{basket.product.name}}</h6>
                            <small class="text-muted">{{basket.quantity }} шт.</small>
                        </div>
                        <span class="text-muted">{{basket.sum }} руб.</span>
                    </li>
                    {% endfor %}


                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{user.basket_set.all.total_sum }} руб.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action="{% url 'orders:order_create' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{form.first_name.id_for_label}}" class="form-label">Имя</label>
                            {{form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{form.last_name.id_for_label}}" class="form-label">Фамилия</label>
                            {{form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{form.email.id_for_label}}" class="form-label">Адрес электронной почты</label>
                            {{form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{form.address.id_for_label}}" class="form-label">Адрес</label>
                            {{form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказ №12345</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">
                            Худи черного цвета с монограммами adidas Originals
                        </th>
                        <td>1</td>
                        <td>6 090,00 руб.</td>
                        <td>6 090,00 руб.</td>
                    </tr>
                    <tr>
                        <th scope="row">
                            Синяя куртка The North Face
                        </th>
                        <td>1</td>
                        <td>23 725,00 руб.</td>
                        <td>23 725,00 руб.</td>
                    </tr>
                    <tr>
                        <th scope="row">
                            Коричневый спортивный oversized-топ ASOS DESIGN
                        </th>
                        <td>2</td>
                        <td>3 390,00 руб.</td>
                        <td>6 780,00 руб.</td>
                    </tr>
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Итого 36 595,00 руб.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}
                        <tr>
                        <th scope="row">{{order.id}}</th>
                        <td>{{order.get_status_display}}</td>
                        <td>{{order.created}}</td>
                        <td> {{order.initiator.basket_set.all.total_sum}} руб.</td>
                        <td>
                            <a href="order.html">просмотреть</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>
                            Ваш заказ успешно сформирован.
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}